### ISSUE TITLE
Support for El Capitan

### ISSUE THREAD

**Issue by TadeasKriz** [insidegui/PlayAlways#1]
Hi, I'm kinda stuck on El Capitan and I'd like to use this app. However it's locked to 10.12+ so I can't run it. Would it be possible to lower the SDK requirement? Thanks!

**Comment by insidegui** [comment]
Yeap, will do

**Comment by TadeasKriz** [comment]
Awesome, thank you!

**Comment by insidegui** [comment]
Done, 0.1.1 supports El Capitan -> https://github.com/insidegui/PlayAlways/releases/tag/0.1.1
