### ISSUE TITLE
Automatically open created playground

### ISSUE THREAD

**Issue by TadeasKriz** [insidegui/PlayAlways#2]
Would it make sense to automatically open the created playground? It seems to me that it might bring quite a lot of value.

**Comment by insidegui** [comment]
It already does. If it's not doing that for you, it's a bug.

**Comment by TadeasKriz** [comment]
Oh, are there any logs I might send you?

**Comment by insidegui** [comment]
You can look at the console while you create a playground and see if anything related appears :)

What version of macOS are you running?

**Comment by insidegui** [comment]
Ah, it is an issue with paths which contain spaces. I will change the method used to open the files and fix this. Thanks for reporting!
