### ISSUE TITLE
Should have an option to allow automatic delete created playground

### ISSUE THREAD

**Issue by oldtrafford91** [insidegui/PlayAlways#5]
I usually use playground for experimenting and don't want to save it. So it would be nice if it is automatically deleted after closing file. For saving, we can duplicate file by Xcode.

**Comment by insidegui** [comment]
Our goal with PlayAlways is to allow the fast creation of playgrounds and keep them around for later study or usage. If you want to create temporary playgrounds that get deleted later, you can always choose to save them in `/tmp` ;)

You can also use [PlayNow](https://github.com/marcboquet/PlayNow)
